image: yikaus/alpine-bash

before_script:
    - apk update && apk add make g++
    
stages:
    - build
    - test
    
build:
    stage: build
    script:
        - cd build
        - make all
        
tests:
    stage: test
    script:
        - cd build
        - make tests
        - ./tests
